### PR TITLE
Update View Command GUI

### LINKED ISSUE #77: List View of all members should display a tangible marker if there is a session on the current day, and if that member has attended or not

### LINKED ISSUE #78: In `view`, the dates of all sessions which the `Person` has attended should be displayed

### PR DESCRIPTION
**Pull request by superb-sushi**
Fixes #78 
Fixes #77

### CODE REVIEW

**Review by weiliann — CHANGES_REQUESTED** [review]
Looks like there are some checkstyle issues causing the build to fail. You can try `gradle check` to locate the issues.

**Comment by superb-sushi** [comment]
> Looks like there are some checkstyle issues causing the build to fail. You can try `gradle check` to locate the issues.

Thanks for the feedback. Checkstyle requirements have been added.

**Review by weiliann — APPROVED** [review]
LGTM

**Review by Rachelcoll — APPROVED** [review]
LGTM

**Pull request merged**
